### ISSUE TITLE
Maybe it's a dumb question, I'm new on nodejs

### ISSUE THREAD

**Issue by Mordecai71** [provotum/frontend#12]
E7440:~/provotum/frontend$ sudo npm install
npm WARN tar ENOENT: no such file or directory, open '/home/mordecai/provotum/frontend/node_modules/.staging/escodegen-1f46070f/bin/escodegen.js'
npm WARN tar ENOENT: no such file or directory, open '/home/mordecai/provotum/frontend/
node_modules/.staging/escodegen-1f46070f/bin/esgenerate.js'
...
npm ERR! err.code.match is not a function

npm ERR! A complete log of this run can be found in:

npm ERR! err.code.match is not a function

E7440:~/provotum/frontend$ npm start -s
/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:328
        throw e;
        ^
Error: Couldn't find preset "react" relative to directory "/home/mordecai/provotum/frontend"

E7440:~/provotum/frontend$ npm --version 
6.9.0
E7440:~/provotum/frontend$ nodejs --version
v8.10.0

**Comment by Mordecai71** [comment]
It was a dumb question. Solved installing nvm to manage npm packages and nodejs versions.

**Comment by rmatil** [comment]
Great 👍
